//Localhost
### Get all contacts
GET http://localhost:3000/contacts

### Update a contact
PUT http://localhost:3000/contacts/678458c6166cc43d8a539a91
content-type: application/json

{
    "firstName": "Ashley Naomi",
    "lastName": "Estigarribia Toledo",
    "email": "nkulas0@rediffmail.com",
    "favoriteColor": "red",
    "birthday": "November 09"
}
### Delete a contact
DELETE http://localhost:3000/contacts/678458c6166cc43d8a539a91

### Create a contact
POST http://localhost:3000/contacts
content-type: application/json

{
    "firstName": "Angelo",
    "lastName": "Esti",
    "email": "nkulas0@rediffmail.com",
    "favoriteColor": "gray",
    "birthday": "January 06"
}